# Generated by Django 5.1.5 on 2025-01-27 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateTimeField()),
                ('category', models.CharField(choices=[('estadistica_informacion', 'Estadística e Información'), ('planeacion_estrategia', 'Planeación y Estrategia'), ('procesos_r', 'Procesos /R'), ('alianzas', 'Alianzas')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completada')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alianza', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
