# Generated by Django 5.1.5 on 2025-02-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('in_progress', 'En Proceso'), ('due_soon', 'Próximo a Vencer'), ('overdue', 'Venció'), ('completed', 'Finalizado')], default='in_progress', max_length=15),
        ),
    ]
