# Generated by Django 5.1.5 on 2025-02-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_task_content_type_remove_task_object_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('estadistica_informacion', 'Estadística e Información'), ('planeacion_estrategia', 'Planeación y Estrategia'), ('procesos_r', 'Procesos /R'), ('alianzas', 'Alianzas')], max_length=30)),
                ('status', models.CharField(choices=[('in_progress', 'En Proceso'), ('due_soon', 'Próximo a Vencer'), ('overdue', 'Venció'), ('completed', 'Finalizado')], default='in_progress', max_length=15)),
                ('evaluation_day', models.CharField(choices=[('monday', 'Lunes'), ('tuesday', 'Martes'), ('wednesday', 'Miércoles'), ('thursday', 'Jueves'), ('friday', 'Viernes')], max_length=10)),
            ],
        ),
    ]
